baseURL = "http://docs.joinmastodon.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[menu]
  [[menu.docs]]
    name = "User guide"
    weight = 1
    identifier = "usage"
    url = "/usage/"
  [[menu.docs]]
    name = "Administrator guide"
    weight = 2
    identifier = "administration"
    url = "/administration/"
  [[menu.docs]]
    name = "Developer guide"
    weight = 3
    identifier = "development"
    url = "/development/"
  [[menu.docs]]
    name = "API"
    weight = 4
    identifier = "api"
    url = "/api/"
